GET http://localhost:8080/companies
Accept: application/json

###

GET http://localhost:8080/companies/bb0c03d6-20f6-4914-be84-69bb899a9eca
Accept: application/json

###

POST http://localhost:8080/companies
#Accept: application/json
Content-Type: application/json

{
    "name": "Logistics 4",
    "registrationNumber": "Magalu"
}

###

GET https://a2fa188f-7b2b-41fa-b4d4-18aae59f1fef.mock.pstmn.io/sanctions/companies/56
#GET http://localhost:4500/sanctions/companies/registrationNumber
Accept: application/json
Content-Type: application/json

