GET http://localhost:8080/companies
Accept: application/json

###

GET http://localhost:8080/companies/bb0c03d6-20f6-4914-be84-69bb899a9eca
Accept: application/json

###

POST http://localhost:8080/companies
#Accept: application/json
Content-Type: application/json

{
    "name": "Logistics-123",
    "registrationNumber": "Log-123"
}

###

#GET http://localhost:4500/sanctions/companies/registrationNumber
GET http://localhost:3001/sanctions/companies/56
X-API-KEY: kyc-secret-123
#Accept: application/json
#Content-Type: application/json
