spring.application.name=522-marketPlaceEventos

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bcsantander_522aula?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}


management.endpoint.health.show-details=always

# variáveis de ambiente para produção
# nano ~/.bashrc
# export DDL_AUTO="validate"
# export DB_URL="jdbc:mysql://localhost:3306/bcsantander_522aula?createDatabaseIfNotExist=true&serverTimezone=UTC"
# export DB_USER="seu_usuario_da_vm"
# export DB_PASS="sua_senha_da_vm"