spring.application.name=522-marketPlaceEventos

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bcsantander_522aula?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
management.endpoint.health.show-details=always
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# variáveis de ambiente para produção
# nano ~/.bashrc
# export DDL_AUTO="validate"
# export DB_URL="jdbc:mysql://localhost:3306/bcsantander_522aula?createDatabaseIfNotExist=true&serverTimezone=UTC"
# export DB_USER="seu_usuario_da_vm"
# export DB_PASS="sua_senha_da_vm"

# Ativa virtual threads
spring.threads.virtual.enabled=true

# Ativa cache com Redis
spring.data.redis.client-type=jedis

# Registration (MySQL 3306)
registration.datasource.url=jdbc:mysql://localhost:3306/bcsantander_522aula?createDatabaseIfNotExist=true&serverTimezone=UTC
registration.datasource.username=root
registration.datasource.password=
registration.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
registration.jpa.properties.hibernate.hbm2ddl.auto=update

# Catalog (MySQL 3307)
catalog.datasource.url=jdbc:mysql://localhost:3307/bcsantander_522catalog?createDatabaseIfNotExist=true&serverTimezone=UTC
catalog.datasource.username=root
catalog.datasource.password=
catalog.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
catalog.jpa.properties.hibernate.hbm2ddl.auto=update
spring.mongodb.representation.uuid=standard
catalog.redis.host=localhost
catalog.redis.port=6379

# MongoDB EventMetadata
# opcional quando usa dados padrão sem usuário/senha porta 27017 banco test.
# spring.mongodb.uri=mongodb://seu_usuario:sua_senha@localhost:27017/meu_banco_marketplace?authSource=admin

# Redis cache
# opcional também em ambiente de desenvolvimento sem usuário e sem senha e na porta 6379
# spring.data.redis.url=redis://default_ou_usuário_ou_em_brancoSeNãoTiverUsuário:sua_senha_aqui@localhost:6379

# Postgres 5432 Ticketing
ticketing.datasource.url=jdbc:postgresql://localhost:5432/bcsantander_522_ticketing?options=-c%20timezone=UTC
ticketing.datasource.username=postgres
ticketing.datasource.password=
ticketing.datasource.driver-class-name=org.postgresql.Driver
ticketing.jpa.properties.hibernate.hbm2ddl.auto=update
ticketing.redis.host=localhost
ticketing.redis.port=6381
