# @no-cookie-jar
POST http://localhost:8080/api/auth/login
Content-Type: application/json
#Accept: application/json

{
  "username": "logistics",
  "password": "password"
}

###
GET http://localhost:8080
// influencer
#Cookie: JSESSIONID=7BA8A7B992C2F446DB1C79CDA295D77B
// brand
Cookie: JSESSIONID=7D34735076E3F5A68C438ECFFC033870