# @no-cookie-jar
POST http://localhost:8080/api/auth/login
Content-Type: application/json
#Accept: application/json

//  "username": "fitness_vibe",
{
  "username": "logistics",
  "password": "password"
}

###
GET http://localhost:8080
// influencer
Cookie: JSESSIONID=B818918E8BF8B2C3C436BAE1D3787F8A
// brand
#Cookie: JSESSIONID=10565A059EBB1CD738BA927A6BEE99DF

###
GET http://localhost:8080/influencer
Cookie: JSESSIONID=B818918E8BF8B2C3C436BAE1D3787F8A

###
GET http://localhost:8080/brand
Cookie: JSESSIONID=806E9859931B92F59C023A3BD56024BE
