POST http://localhost:8080/eventMetadatas
Content-Type: application/json

{
  "eventId": "bb59ff18-d0dd-4911-9880-2bca64283a19",
  "eventDescription": "Turnê de despedida 222",
  "technicalRequirements": {
    "soundSystem": "Line away",
    "minAge": "16",
    "backspace_pass_avaliable": "true"
  },
  "sectors": [
    { "name": "Premium", "price":  450.00},
    { "name": "Arquibancada", "price":  200.00}
  ],
  "seats": [
    { "code": "PRE-01", "sectorName":  "Premium"},
    { "code": "ARQ-10", "sectorName":  "Arquibancada"}
  ]
}

<> 2026-08-03T213719.201.json