POST http://localhost:8080/eventMetadatas
Content-Type: application/json

{
  "eventId": "2e108c97-a858-4cd6-9450-da143e8b6459",
  "eventDescription": "Turnê de despedida",
  "technicalRequirements": {
    "soundSystem": "Line away",
    "minAge": "16",
    "backspace_pass_avaliable": "true"
  },
  "sectors": [
    { "name": "Premium", "price":  450.00},
    { "name": "Arquibancada", "price":  200.00}
  ],
  "seats": [
    { "code": "PRE-01", "sectorName":  "Pista Premium"},
    { "code": "ARQ-10", "sectorName":  "Arquibancada"}
  ]
}

<> 2026-08-03T213719.201.json