POST http://localhost:8080/eventMetadatas
Content-Type: application/json

{
  "eventId": "4921e2a3-99b7-42f6-8739-c016545f1d59",
  "eventDescription": "Turnê de despedida - marcar assento",
  "technicalRequirements": {
    "soundSystem": "Line away",
    "minAge": "16",
    "backspace_pass_avaliable": "true"
  },
  "sectors": [
    { "name": "Premium", "price":  450.00},
    { "name": "Arquibancada", "price":  200.00}
  ],
  "seats": [
    { "code": "PRE-01", "sectorName":  "Premium"},
    { "code": "ARQ-10", "sectorName":  "Arquibancada"}
  ]
}

<> 2026-08-03T213719.201.json