spring.application.name=533-proposal_manager

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bcsantander_533aula_proposal_manager?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# Adiciona detalhes da saúde em localhost:8080/actuator/health - precisa da dependência actuator
management.endpoint.health.show-details=always
