spring.application.name=542-compliance

spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.sanction-client.url=http://localhost:3001
spring.cloud.openfeign.client.config.sanction-client.logger-level=full
spring.cloud.openfeign.client.config.sanction-client.default-request-headers.X-API-KEY: kyc-secret-123

spring.cloud.openfeign.client.config.aml-client.url=http://localhost:3002
spring.cloud.openfeign.client.config.aml-client.logger-level=full
spring.cloud.openfeign.client.config.aml-client.default-request-headers.authorization: Bearer xyz123


logging.level.com.devrodrigo._542_compliance.infrastructure.rest=debug