spring.application.name=542-compliance

spring.cloud.openfeign.client.config.sanction-client.url=https://a2fa188f-7b2b-41fa-b4d4-18aae59f1fef.mock.pstmn.io
spring.cloud.openfeign.client.config.sanction-client.logger-level=full
