### GET request to example server
GET http://localhost:8080/api/chat-model?prompt=oi
###

GET http://localhost:8080/api/chat-client?prompt=Boa tarde, tudo bem?
###

POST http://localhost:8080/api-whisper-puro/transcribe HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="recording-3.m4a"

< ../../src/test/resources/audio/recording-3.m4a
--boundary

###

POST http://localhost:8080/api-consulta-api-oficial/transcribe HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="recording-3.m4a"

< ../../src/test/resources/audio/recording-3.m4a
--boundary

###

POST http://localhost:8080/api/sinthesize
Content-Type: application/json

{
"text": "O que me diz sobre o dia?"
}

###
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "description": "Compra no mercadinho 4",
  "category": "GROCERIES",
  "amount": 12534
}

###
GET http://localhost:8080/transactions/GROCERIES
###
GET http://localhost:8080/transactions/PHARMA
###
GET http://localhost:8080/transactions/AUTO
###
POST http://localhost:8080/transactions/ai-api-whisper-puro HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="recording-2.m4a"

< ../../src/test/resources/audio/recording-2.m4a
--boundary

###
POST http://localhost:8080/transactions/ai-api-openai HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="recording-1.m4a"

< ../../src/test/resources/audio/recording-1.m4a
--boundary

###
