spring.application.name=612-budgetingProjFinalComIA
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4o-mini // antigo
spring.ai.openai.chat.base-url=http://192.168.100.10:1234/v1
spring.ai.openai.chat.model=qwen/qwen3-v1-8b
spring.ai.openai.chat.temperature=0.8
spring.ai.openai.chat.max-tokens=800
spring.ai.openai.chat.response-format.type=TEXT
logging.level.org.springframework.ai=DEBUG
