spring.application.name=612-budgetingProjFinalComIA
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4o-mini // antigo
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.temperature=0.8
spring.ai.openai.chat.response-format.type=TEXT

